#!/usr/bin/env python3
"""Extract the legacy catalog without importing/running the legacy web server."""
import argparse
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def literal_assignment(tree, name):
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == name for target in node.targets):
            try:
                return ast.literal_eval(node.value)
            except ValueError:
                continue
    raise ValueError(f"Missing literal assignment: {name}")


def sql(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def infer_mood(genre):
    genre = (genre or '').lower()
    for mood, fragments in [
        ('Sad', ['ballad', 'romance', 'r&b', 'soul']),
        ('Angry', ['hip hop', 'dancehall', 'alternative rock']),
        ('Exhausted', ['classical', 'ambient', 'acoustic']),
        ('Neutral', ['synthwave', 'indie pop', 'electropop', 'pop rock']),
        ('Happy', ['dance pop', 'house', 'funk', 'latin pop', 'dance', 'pop']),
    ]:
        if any(fragment in genre for fragment in fragments):
            return mood
    return 'Neutral'


def render():
    tree = ast.parse((ROOT / 'moosic-backend/main.py').read_text())
    catalog = literal_assignment(tree, 'artists')
    repairs = literal_assignment(tree, 'KNOWN_AUDIO_REPAIRS')
    unavailable = literal_assignment(tree, 'KNOWN_UNPLAYABLE_TITLES')
    # These two concrete video IDs were already maintained by the old project.
    repairs.update({'Choo Lo': 'https://www.youtube.com/embed/sFMRqxCexDk', 'Soch Hai': 'https://www.youtube.com/embed/dnXGxMlV-rU'})
    verified_repairs = {(r['artist'], r['title']): r['new_source'] for r in json.loads((ROOT / 'supabase/catalog-source-repairs.json').read_text())['repairs']}
    mood_songs = literal_assignment(tree, 'mood_songs')
    cover = 'https://images.unsplash.com/photo-1516280440614-37939bbacd81'
    existing_titles = {track['title'] for artist in catalog for album in artist['albums'] for track in album['songs']}
    catalog.append({'name': 'Moosic Mood Mix', 'image_url': cover, 'albums': [{
        'title': 'Mood Collection', 'release_date': '2026-09-07', 'cover_url': cover,
        'songs': [{'title': title, 'genre': 'Bollywood', 'mood': mood, 'language': 'Hindi', 'duration': None, 'audio_url': None, 'cover_url': cover}
                  for mood, titles in mood_songs.items() for title in titles if title not in existing_titles],
    }]})
    lines = [
        '-- Generated by python3 supabase/scripts/generate_seed.py. Catalog metadata only.',
        '-- Re-running does not overwrite manager edits. YouTube availability is unverified.',
        '-- Missing audio remains unavailable; no fabricated source or silent replacement.',
        'begin;',
    ]
    totals = {'artists': 0, 'albums': 0, 'songs': 0, 'without_audio': 0}
    for artist in catalog:
        totals['artists'] += 1
        artist_ref = f"(select id from public.artists where lower(name) = lower({sql(artist['name'])}))"
        lines.append(f"insert into public.artists(name,image_url) values ({sql(artist['name'])},{sql(artist.get('image_url'))}) on conflict do nothing;")
        for album in artist['albums']:
            totals['albums'] += 1
            album_ref = f"(select id from public.albums where artist_id = {artist_ref} and title = {sql(album['title'])})"
            lines.append(f"insert into public.albums(title,artist_id,release_date,cover_url) values ({sql(album['title'])},{artist_ref},{sql(album.get('release_date'))},{sql(album.get('cover_url'))}) on conflict do nothing;")
            for track in album['songs']:
                totals['songs'] += 1
                audio = verified_repairs.get((artist['name'], track['title']), repairs.get(track['title'], track.get('audio_url')))
                playable = False if not audio or track['title'] in unavailable else None
                totals['without_audio'] += not bool(audio)
                values = [sql(track['title']), artist_ref, album_ref, sql(track.get('genre')), sql(track.get('mood') or infer_mood(track.get('genre'))), sql(track.get('language', 'English')), sql(track.get('duration')), sql(audio), sql(track.get('cover_url')), sql(playable)]
                lines.append('insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values (' + ','.join(values) + ') on conflict do nothing;')
    lines.extend(['commit;', ''])
    return '\n'.join(lines), totals


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'supabase/seed.sql')
    options = parser.parse_args()
    output, counts = render()
    options.output.write_text(output)
    print(f"Wrote {options.output}: {counts}")
