-- Generated from supabase/low-battery-catalog.json by generate_seed.py.
-- Retire only the original unverified sources; retain IDs and library relationships.
-- Existing replacements and manager edits are never overwritten.
begin;
update public.songs set is_playable=FALSE where title='Pathikada Sandhya' and artist_id=(select id from public.artists where lower(name)=lower('Shreya Ghoshal')) and audio_url='https://www.youtube.com/embed/LwjXxs9OVQs';
update public.songs set is_playable=FALSE where title='Gunjan Gaun' and artist_id=(select id from public.artists where lower(name)=lower('Shreya Ghoshal')) and audio_url='https://www.youtube.com/embed/9Z8L8tNJYsE';
update public.songs set is_playable=FALSE where title='Rn Samayal' and artist_id=(select id from public.artists where lower(name)=lower('A.R. Rahman')) and audio_url='https://www.youtube.com/embed/2N7Ar2kGpDY';
insert into public.artists(name) values ('Billie Eilish') on conflict do nothing;
insert into public.albums(title,artist_id,cover_url) values ('everything i wanted',(select id from public.artists where lower(name)=lower('Billie Eilish')),'https://i.ytimg.com/vi/EgBJmlPo8Xw/hqdefault.jpg') on conflict do nothing;
insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values ('everything i wanted',(select id from public.artists where lower(name)=lower('Billie Eilish')),(select id from public.albums where artist_id=(select id from public.artists where lower(name)=lower('Billie Eilish')) and title='everything i wanted'),'Ambient Pop','Exhausted','English',288,'https://www.youtube.com/embed/EgBJmlPo8Xw','https://i.ytimg.com/vi/EgBJmlPo8Xw/hqdefault.jpg',NULL) on conflict do nothing;
insert into public.artists(name) values ('Coldplay') on conflict do nothing;
insert into public.albums(title,artist_id,cover_url) values ('Parachutes',(select id from public.artists where lower(name)=lower('Coldplay')),'https://i.ytimg.com/vi/1aokooixKIo/hqdefault.jpg') on conflict do nothing;
insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values ('Sparks',(select id from public.artists where lower(name)=lower('Coldplay')),(select id from public.albums where artist_id=(select id from public.artists where lower(name)=lower('Coldplay')) and title='Parachutes'),'Acoustic Rock','Exhausted','English',227,'https://www.youtube.com/embed/1aokooixKIo','https://i.ytimg.com/vi/1aokooixKIo/hqdefault.jpg',NULL) on conflict do nothing;
insert into public.artists(name) values ('Cigarettes After Sex') on conflict do nothing;
insert into public.albums(title,artist_id,cover_url) values ('Cigarettes After Sex',(select id from public.artists where lower(name)=lower('Cigarettes After Sex')),'https://i.ytimg.com/vi/sElE_BfQ67s/hqdefault.jpg') on conflict do nothing;
insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values ('Apocalypse',(select id from public.artists where lower(name)=lower('Cigarettes After Sex')),(select id from public.albums where artist_id=(select id from public.artists where lower(name)=lower('Cigarettes After Sex')) and title='Cigarettes After Sex'),'Dream Pop','Exhausted','English',290,'https://www.youtube.com/embed/sElE_BfQ67s','https://i.ytimg.com/vi/sElE_BfQ67s/hqdefault.jpg',NULL) on conflict do nothing;
insert into public.artists(name) values ('Lord Huron') on conflict do nothing;
insert into public.albums(title,artist_id,cover_url) values ('Strange Trails',(select id from public.artists where lower(name)=lower('Lord Huron')),'https://i.ytimg.com/vi/KtlgYxa6BMU/hqdefault.jpg') on conflict do nothing;
insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values ('The Night We Met',(select id from public.artists where lower(name)=lower('Lord Huron')),(select id from public.albums where artist_id=(select id from public.artists where lower(name)=lower('Lord Huron')) and title='Strange Trails'),'Indie Folk','Exhausted','English',208,'https://www.youtube.com/embed/KtlgYxa6BMU','https://i.ytimg.com/vi/KtlgYxa6BMU/hqdefault.jpg',NULL) on conflict do nothing;
insert into public.artists(name) values ('Bon Iver') on conflict do nothing;
insert into public.albums(title,artist_id,cover_url) values ('Bon Iver, Bon Iver',(select id from public.artists where lower(name)=lower('Bon Iver')),'https://i.ytimg.com/vi/TWcyIpul8OE/hqdefault.jpg') on conflict do nothing;
insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values ('Holocene',(select id from public.artists where lower(name)=lower('Bon Iver')),(select id from public.albums where artist_id=(select id from public.artists where lower(name)=lower('Bon Iver')) and title='Bon Iver, Bon Iver'),'Indie Folk','Exhausted','English',344,'https://www.youtube.com/embed/TWcyIpul8OE','https://i.ytimg.com/vi/TWcyIpul8OE/hqdefault.jpg',NULL) on conflict do nothing;
insert into public.artists(name) values ('Joji') on conflict do nothing;
insert into public.albums(title,artist_id,cover_url) values ('BALLADS 1',(select id from public.artists where lower(name)=lower('Joji')),'https://i.ytimg.com/vi/K3Qzzggn--s/hqdefault.jpg') on conflict do nothing;
insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values ('SLOW DANCING IN THE DARK',(select id from public.artists where lower(name)=lower('Joji')),(select id from public.albums where artist_id=(select id from public.artists where lower(name)=lower('Joji')) and title='BALLADS 1'),'Alternative R&B','Exhausted','English',217,'https://www.youtube.com/embed/K3Qzzggn--s','https://i.ytimg.com/vi/K3Qzzggn--s/hqdefault.jpg',NULL) on conflict do nothing;
insert into public.artists(name) values ('Novo Amor') on conflict do nothing;
insert into public.albums(title,artist_id,cover_url) values ('Bathing Beach',(select id from public.artists where lower(name)=lower('Novo Amor')),'https://i.ytimg.com/vi/OmKAn8rNbKg/hqdefault.jpg') on conflict do nothing;
insert into public.songs(title,artist_id,album_id,genre,mood,language,duration,audio_url,cover_url,is_playable) values ('Anchor',(select id from public.artists where lower(name)=lower('Novo Amor')),(select id from public.albums where artist_id=(select id from public.artists where lower(name)=lower('Novo Amor')) and title='Bathing Beach'),'Indie Folk','Exhausted','English',256,'https://www.youtube.com/embed/OmKAn8rNbKg','https://i.ytimg.com/vi/OmKAn8rNbKg/hqdefault.jpg',NULL) on conflict do nothing;
commit;
