-- Supabase is the source of truth for Auth, data, and licensed audio uploads.
create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  username text not null check (char_length(username) between 1 and 32),
  email text not null,
  role text not null default 'user' check (role in ('user', 'manager')),
  is_premium boolean not null default false,
  profile_note text not null default '' check (char_length(profile_note) <= 180),
  created_at timestamptz not null default now()
);
create unique index profiles_username_lower_key on public.profiles(lower(username));
create unique index profiles_email_lower_key on public.profiles(lower(email));

create function public.current_profile_id() returns bigint
language sql stable security definer set search_path = '' as $$
  select id from public.profiles where auth_user_id = (select auth.uid())
$$;
create function public.is_manager() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where auth_user_id = (select auth.uid()) and role = 'manager')
$$;
create function public.has_premium() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where auth_user_id = (select auth.uid()) and is_premium)
$$;
revoke all on function public.current_profile_id(), public.is_manager(), public.has_premium() from public;
grant execute on function public.current_profile_id(), public.is_manager(), public.has_premium() to authenticated;

create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
declare requested_username text;
begin
  requested_username := left(trim(coalesce(new.raw_user_meta_data ->> 'username', '')), 32);
  if requested_username = '' then requested_username := 'listener_' || left(replace(new.id::text, '-', ''), 20); end if;
  -- User metadata is untrusted: it can never assign role or premium access.
  insert into public.profiles(auth_user_id, name, username, email)
  values (new.id, left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), 'Listener'), 100), requested_username, new.email);
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create function public.sync_profile_email() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.profiles set email = new.email where auth_user_id = new.id;
  return new;
end $$;
create trigger on_auth_email_updated after update of email on auth.users for each row execute function public.sync_profile_email();
revoke all on function public.handle_new_user(), public.sync_profile_email() from public;

create table public.artists (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 200),
  image_url text
);
create unique index artists_name_lower_key on public.artists(lower(name));
create table public.albums (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 200),
  artist_id bigint references public.artists(id) on delete set null,
  release_date text,
  cover_url text,
  unique(artist_id, title)
);
create table public.songs (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 200),
  artist_id bigint references public.artists(id) on delete set null,
  album_id bigint references public.albums(id) on delete set null,
  genre text,
  mood text,
  language text not null default 'English',
  duration integer check (duration >= 0),
  audio_url text,
  cover_url text,
  is_playable boolean,
  audio_checked_at timestamptz,
  unique(artist_id, title)
);
create index songs_artist on public.songs(artist_id);
create index songs_album on public.songs(album_id);
create index songs_mood on public.songs(mood);
create index songs_genre on public.songs(genre);
create index songs_language on public.songs(language);
create index albums_artist on public.albums(artist_id);

create table public.playlists (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 200),
  cover_url text,
  description text check (char_length(description) <= 2000),
  is_deleted boolean not null default false,
  deleted_at timestamptz
);
create index playlists_user_deleted on public.playlists(user_id, is_deleted);
create table public.playlist_songs (
  id bigint generated by default as identity primary key,
  playlist_id bigint not null references public.playlists(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  position integer not null default 0 check(position >= 0),
  unique(playlist_id, song_id)
);
create index playlist_songs_position on public.playlist_songs(playlist_id, position, id);
create index playlist_songs_song on public.playlist_songs(song_id);
create table public.liked_songs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  unique(user_id, song_id)
);
create table public.downloads (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  downloaded_at timestamptz not null default now(),
  unique(user_id, song_id)
);
create table public.listening_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  played_at timestamptz not null default now(),
  progress_seconds integer not null default 0 check(progress_seconds between 0 and 86400),
  completed boolean not null default false,
  skipped boolean not null default false
);
create index history_user_played on public.listening_history(user_id, played_at desc);
create table public.playback_states (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.profiles(id) on delete cascade,
  song_id bigint references public.songs(id) on delete set null,
  position_seconds integer not null default 0 check(position_seconds between 0 and 86400),
  is_playing boolean not null default false,
  updated_at timestamptz not null default now()
);
create table public.queue_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  position integer not null check(position >= 0),
  added_at timestamptz not null default now()
);
create index queue_user_position on public.queue_items(user_id, position, id);
create table public.payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  plan text not null,
  amount numeric(12,2) not null check(amount >= 0),
  currency text not null,
  status text not null check(status in ('success', 'failed', 'pending', 'refunded', 'legacy_test')),
  provider_event_id text unique,
  payment_date timestamptz not null default now()
);
create index payments_user on public.payments(user_id);

alter table public.profiles enable row level security;
create policy profiles_read on public.profiles for select to authenticated using (auth_user_id = (select auth.uid()) or (select public.is_manager()));
create policy profiles_update on public.profiles for update to authenticated using (auth_user_id = (select auth.uid())) with check (auth_user_id = (select auth.uid()));
-- Column privileges close the RLS trap where a user updates their own role.
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update(name, username, profile_note) on public.profiles to authenticated;

do $$
declare t text;
begin
  foreach t in array array['artists', 'albums', 'songs'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy catalog_read on public.%I for select to anon, authenticated using (true)', t);
    execute format('create policy catalog_manage on public.%I for all to authenticated using ((select public.is_manager())) with check ((select public.is_manager()))', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant select on public.%I to anon, authenticated', t);
    execute format('grant insert, update, delete on public.%I to authenticated', t);
  end loop;
  foreach t in array array['playlists', 'liked_songs', 'listening_history', 'playback_states', 'queue_items'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy owner_access on public.%I for all to authenticated using (user_id = (select public.current_profile_id())) with check (user_id = (select public.current_profile_id()))', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;
alter table public.playlist_songs enable row level security;
create policy playlist_song_owner on public.playlist_songs for all to authenticated
using (exists(select 1 from public.playlists p where p.id = playlist_id and p.user_id = (select public.current_profile_id())))
with check (exists(select 1 from public.playlists p where p.id = playlist_id and p.user_id = (select public.current_profile_id()) and not p.is_deleted));
revoke all on public.playlist_songs from anon, authenticated;
grant select, insert, update, delete on public.playlist_songs to authenticated;
alter table public.downloads enable row level security;
create policy downloads_owner on public.downloads for all to authenticated
using (user_id = (select public.current_profile_id()) and (select public.has_premium()))
with check (user_id = (select public.current_profile_id()) and (select public.has_premium()));
revoke all on public.downloads from anon, authenticated;
grant select, insert, update, delete on public.downloads to authenticated;
alter table public.payments enable row level security;
create policy payments_read on public.payments for select to authenticated using (user_id = (select public.current_profile_id()) or (select public.is_manager()));
revoke all on public.payments from anon, authenticated;
grant select on public.payments to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Only managers or verified server-side billing may change entitlements.
create function public.manager_set_premium(target_user_id bigint, enabled boolean) returns public.profiles
language plpgsql security definer set search_path = '' as $$
declare result public.profiles;
begin
  if not public.is_manager() then raise exception 'Manager access required' using errcode = '42501'; end if;
  update public.profiles set is_premium = enabled where id = target_user_id and role <> 'manager' returning * into result;
  if not found then raise exception 'User not found or protected manager account' using errcode = 'P0002'; end if;
  return result;
end $$;
create function public.cancel_premium() returns void
language sql security definer set search_path = '' as $$
  update public.profiles set is_premium = false where auth_user_id = (select auth.uid())
$$;
-- Reordering is atomic and verifies the complete set, avoiding partially saved orders.
create function public.reorder_playlist(target_playlist_id bigint, song_ids bigint[]) returns void
language plpgsql security invoker set search_path = '' as $$
declare existing_ids bigint[];
begin
  perform 1 from public.playlists where id = target_playlist_id and user_id = public.current_profile_id() and not is_deleted for update;
  if not found then raise exception 'Playlist not found' using errcode = 'P0002'; end if;
  select coalesce(array_agg(song_id order by song_id), '{}'::bigint[]) into existing_ids from public.playlist_songs where playlist_id = target_playlist_id;
  if existing_ids is distinct from (select coalesce(array_agg(i order by i), '{}'::bigint[]) from unnest(song_ids) as i) then
    raise exception 'song_ids must contain every playlist song exactly once' using errcode = '22023';
  end if;
  update public.playlist_songs p set position = n.position::integer - 1
  from unnest(song_ids) with ordinality as n(song_id, position)
  where p.playlist_id = target_playlist_id and p.song_id = n.song_id;
end $$;
create function public.append_queue(target_song_id bigint) returns public.queue_items
language plpgsql security invoker set search_path = '' as $$
declare result public.queue_items; owner_id bigint := public.current_profile_id();
begin
  perform pg_advisory_xact_lock(owner_id);
  insert into public.queue_items(user_id, song_id, position)
  select owner_id, target_song_id, coalesce(max(position) + 1, 0) from public.queue_items where user_id = owner_id returning * into result;
  return result;
end $$;
revoke all on function public.manager_set_premium(bigint, boolean), public.cancel_premium(), public.reorder_playlist(bigint, bigint[]), public.append_queue(bigint) from public;
grant execute on function public.manager_set_premium(bigint, boolean), public.cancel_premium(), public.reorder_playlist(bigint, bigint[]), public.append_queue(bigint) to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values
  ('music', 'music', true, 52428800, array['audio/mpeg', 'audio/mp4', 'audio/ogg', 'audio/wav', 'audio/x-wav', 'audio/flac', 'audio/webm']),
  ('covers', 'covers', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif']),
  ('avatars', 'avatars', true, 2097152, array['image/jpeg', 'image/png', 'image/webp'])
on conflict(id) do nothing;
create policy catalog_media_read on storage.objects for select to anon, authenticated using(bucket_id in ('music', 'covers', 'avatars'));
create policy catalog_media_manage on storage.objects for all to authenticated
using(bucket_id in ('music', 'covers') and (select public.is_manager()))
with check(bucket_id in ('music', 'covers') and (select public.is_manager()));
create policy avatars_owner on storage.objects for all to authenticated
using(bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check(bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);
